# Generated by Django 5.2.14 on 2026-05-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_add_subscriber_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio_emoji', models.CharField(default='👋', max_length=10)),
                ('bio_title', models.CharField(default='Bienvenue sur papobilou', max_length=200)),
                ('bio_content', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Configuration du site',
            },
        ),
    ]
